### ISSUE TITLE
Download of trash-folder patch fails

### ISSUE THREAD

**Issue by goerz** [x-way/homebrew-mutt#1]
There seems to be a problem with the SSL:

```
goerz@ophelia:~> brew install x-way/mutt/mutt --with-trash-patch
==> Installing mutt from x-way/homebrew-mutt
==> Downloading https://bitbucket.org/mutt/mutt/downloads/mutt-1.5.24.tar.gz
Already downloaded: /Library/Caches/Homebrew/mutt-1.5.24.tar.gz
==> Downloading https://blog.x-way.org/stuff/mutt-1.5.24-trash_folder.diff

curl: (35) Unknown SSL protocol error in connection to blog.x-way.org:-36
Error: Failed to download resource "mutt--patch"
Download failed: https://blog.x-way.org/stuff/mutt-1.5.24-trash_folder.diff
```

**Comment by x-way** [comment]
Thanks for reporting this. What is the output of the following three commands?
- `brew install -vd x-way/mutt/mutt --with-trash-patch`
- `curl -V`
- `curl -sv https://blog.x-way.org/stuff/mutt-1.5.24-trash_folder.diff`

**Comment by goerz** [comment]
Must have been a networking issue (I encountered this while using an Amtrak on-train WiFi access point). I just tried it again from the office and now it works flawlessly. So, this can probably be closed as "non-reproducible"
